# Generated by Django 4.2 on 2024-10-27 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cita', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('Hora_cita', models.DateTimeField(verbose_name='Hora')),
                ('Dia_cita', models.CharField(max_length=20, verbose_name='Día')),
                ('MedicoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medico.medico', verbose_name='Medico')),
                ('PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name_plural': 'Cita',
            },
        ),
    ]
